
services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - BRAVE_SEARCH_KEY=${BRAVE_SEARCH_KEY}
      - ALLOWED_CHAT_IDS=${ALLOWED_CHAT_IDS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - telegram-bot-network


  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - telegram-bot-network

networks:
  telegram-bot-network:
    name: telegram-bot-network
    driver: bridge